services:
  webfrontend:    
    build:
      context: .
      dockerfile: WebFrontEnd/Dockerfile

  webapi:    
    build:
      context: .
      dockerfile: WebApi/Dockerfile

  redis:
   image: redis