services:
  webfrontend:    
    image: frontend:1.0
    container_name: frontend
    hostname: frontend
    build:
      context: .
      dockerfile: WebFrontEnd/Dockerfile

  webapi:
    image: webapi:1.0
    container_name: webapi
    hostname: webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile

  redis:
   image: redis
