services:
  webfrontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Password123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "8081:8080"
      - "443:443"
    
  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080" # 8080 is the default port for .net 8.0 # 80 for .net 6.0

# Generate Certificate
# dotnet dev-certs https -ep %USERPROFILE%\.aspnet\https\aspnetapp.pfx -p Password123
# dotnet dev-certs https --trust

#https://learn.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-9.0
